### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by Wynadorn** [geheur/bank-tag-custom-layouts#19]
FPS drop from 50 to 12 when lots of placeholders (or items) are shown.
Found out after creating a tab with all melee equipment: https://pastebin.com/raw/nxecqssy

**Comment by geheur** [comment]
I saw this once when the plugin bugged and made layout placeholders out of my entire bank. Didn't think anyone would make tabs that large though and immediately forgot about it :P.

Are you sure this happens when lots of items are shown? iirc it had something to do with me rendering all of my layout placeholders even if they're not visible - not due to a large amount of items.

I wonder if caching images would speed stuff up. I'm not sure how expensive itemManager.getImage calls are.

**Comment by geheur** [comment]
Fixed in a5d42d115bee3b17e87b7558e16fc69b8062cc86 by not rendering layout placeholders that wouldn't be visible anyways.
