### ISSUE TITLE
Placeholder menu opens without being clicked on, prevents item withdrawal (vanilla client bug).

### ISSUE THREAD

**Issue by orlp** [geheur/bank-tag-custom-layouts#33]
I've noticed that this plugin does not always seem to respect the Runelite anti-drag settings.

Even stranger, I've noticed that if I drag a piece of gear with left click, sometimes it opens a right click menu. I have recorded this, I can assure that I was only using left click in this GIF:
![bank_layout_glitch](https://user-images.githubusercontent.com/202547/125402705-03f67000-e3b5-11eb-8d4b-50ee806bc152.gif)

**Comment by orlp** [comment]
> I'm aware of the right click menu happening on left click, but I'm not sure
if it has anything to do with this plugin

Hmm, maybe you're right. After some more testing I can reproduce also
in the normal bank. It appears to be triggered when you drag an item onto
a placeholder.

> As for anti drag - are you seeing this on actual bank items/placeholders,
or the transparent placeholder-like items that are specific to this plugin?

I don't know, sorry. It's quite sporadic.

> Also, what
settings do you have in the anti drag plugin?

11 client ticks of delay.

**Comment by geheur** [comment]
Can confirm that the right click menu thing happens in the regular bank. I've also been told it happens on the vanilla client. The issue can be prevented by inserting a high-priority menu entry on placeholders - I'll have to see if there's an elegant way of doing this without all the unwanted side effects of inserting bogus menu entries. Having consistent withdraw behavior on items that isn't affected by items next to the item you're withdrawing would be very nice.

FYI, this issue occurs when your left mouse down is on a regular item but your left mouse up is on a placeholder, and occurs before the antidrag timer expires.

Let me know if you figure out how to reproduce anti-drag not working right, as I've never encountered any issues with it.

**Comment by geheur** [comment]
Also interesting: starting a left-mouse drag on a placeholder and releasing it off the placeholder (anywhere) before the anti-drag timer causes the placeholder to be released.

**Comment by orlp** [comment]
Even if it occurs in the vanilla client, I believe it should be preventable. Perhaps an upstream issue should be made in Runelite.

**Comment by geheur** [comment]
I've submitted a bug report to jagex and I'll ask the Runelite devs if they're willing to fix this.

If the answer is no, I have proof-of-concept for methods that prevent this bug that I'm confidant I can add to this plugin.

**Comment by geheur** [comment]
A workaround for the placeholder right-click menu appearing, and placeholders releasing without clicking the menu option, has been added in 1.4.5.

Since most of the discussion in this issue is about that, and not about inconsistent anti-drag, and the very low amount of information on it, I'm changing the issue title and closing the issue. If you ever get more info on this, feel free to make a new issue.

**Comment by orlp** [comment]
@geheur 

> Let me know if you figure out how to reproduce anti-drag not working right, as I've never encountered any issues with it.

It happened again today. I don't know how to reproduce it but I did notice a big clue. After the inadvertent swap occurred, 
it wasn't just the plugin tab that was affected. The actual item location in the bank was changed, and it didn't just swap—it got moved out of the (real) bank tab it was in into the leftmost bank tab.

Another clue is that this happened with a tab from the [inventory setups](https://github.com/dillydill123/inventory-setups) plugin.

**Comment by geheur** [comment]
This makes me think of a bug that is very rare (I have seen it twice ever) in which you withdraw the item that is in that spot in the real, un-laid-out and un-filtered, bank rather than the one shown in the bank tag. This often happens when you are withdrawing lots of items, as withdrawing items can cause the bank to rebuild itself (triggering both the bank filtering from Bank Tags and the laying out from Bank Tag Layouts), which sounds to me like it might be related. Reasons why I think these two bugs might be related: 1) you can't seem to reproduce it consistently, and 2) the item ended up in the left-most tab, which is from where the incorrect items I withdrew were from.

1. Did the item move into the leftmost bank tab because it was dragged on top of an item in that tab, or was the item it was dragged on top of from a different tab?

Also, given that I'm guessing you weren't dragging one of the fake items my plugin adds as those shouldn't cause movement in the real bank, this likely isn't an issue with my plugin.
