### ISSUE TITLE
Layout Placeholders & POH Storage

### ISSUE THREAD

**Issue by Wynadorn** [geheur/bank-tag-custom-layouts#46]
**Suggestion**
It could be possible for the layout placeholders to indicate if an item is stored in the player's house.

For example:
![image](https://user-images.githubusercontent.com/4095127/142044349-d268797d-d4f3-4c68-9b4a-35f125bb2f89.png)

No idea if Runelite has this data available somewhere, would be easy to implement if so.

**Comment by Wynadorn** [comment]
The same idea could be applied for items in the group storage.

**Comment by geheur** [comment]
Don't think Runelite has that data anywhere.

This sounds different enough from bank tag layouts that it should be a separate plugin that layouts could read the data of to display the layout placeholders differently (could also fix #36 at the same time :P). I guess making a standalone plugin would be more work, as you'd have to create some feature for it to be useful to install (such as a bank tag that shows all of your stored POH items).

If it were just part of layouts, it would be a really strange feature because people would have to add their poh items to a tab which sounds like a lot of work. Most people won't add their items to a bank tag before they put it in their poh.

**Comment by geheur** [comment]
Took a look, this info isn't available when the costume room treasure box isn't open (at least for clue scroll items), so this would have to be cached.

**Comment by Wynadorn** [comment]
> this info isn't available when the costume room treasure box isn't open

Thanks for looking into it, while it would be nice, I'll close this issue for now then as it seems like whole lot of work.

The ability to see (`get()`) the contents of your POH storage could be part of the base Runelite framework if it where made I suppose, as it could be useful for a range of plugins.

>This sounds different enough from bank tag layouts that it should be a separate plugin

Yea, Since the regular bank also has placeholders an indication if an item is stored in the POH should indeed be a separate plugin.
