### ISSUE TITLE
Suggestion to combat how long the list of bank tags are getting

### ISSUE THREAD

**Issue by damnnitbobby** [geheur/bank-tag-custom-layouts#52]
The bank tags on the left side is great and it should stay there, but my suggestion is to add a new left click option which opens a menu containing all the bank tags in a 6 x 4 grid (when the screen is the smallest size). 

You would be able to scroll down in this menu if you had even more bank tags, which I know I sure do. Also you would be able to re-arrange the icons within this menu and it wouldn't effect the order of the icons on the left side of the bank. 

An imgur of this idea can be seen here for additional clarity https://i.imgur.com/Mg8ugri.png

**Comment by geheur** [comment]
lmao you have described the existing feature of bank tags "tag tab tab" almost exactly. I have a PR here https://github.com/runelite/runelite/pull/13332 but I wouldn't mind adding a menu swap for the "view tag tabs" button to this plugin since that PR is fairly stale.

> Also you would be able to re-arrange the icons within this menu and it wouldn't effect the order of the icons on the left side of the bank
This is the only thing you asked for that isn't already possible with tag tab tab as far as I can tell.

**Comment by damnnitbobby** [comment]
Thanks for the quick reply. I don't see "tag tab tab" in the bank tabs plugin. Am I an idiot? https://i.imgur.com/Nf0Kcvn.png

**Comment by damnnitbobby** [comment]
Oh wow, I'm an idiot 😄 
Thanks for the quick reply

**Comment by geheur** [comment]
You can now use "Custom Menu Swaps" hub plugin to swap "View tag tabs", so I don't plan to add anything further in this area.
